version: '3.8'

services:
  client:
    image: node:14.13.0-alpine3.10
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    command: npm run serve
